import{i as n,a as u,S as g}from"./assets/vendor-C_7oAj77.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const f="48551671-8e0bd0e05b8a9090cbea8e4d9";let l=1;async function h(a){const s="https://pixabay.com/api/";try{return l>10?(n.warning({title:"Warning",message:"You have reached the last page!",position:"topRight"}),[]):(await u.get(s,{params:{key:f,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:l}})).data.hits}catch(r){console.error("REQUEST ERROR",r),n.error({title:"Error",message:"Failed to fetch images. Please try again!",position:"topRight"})}}function y(){l=1}function b(){l+=1}function E(a){const s=document.getElementById("gallery");if(a.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}a.forEach(r=>{const i=document.createElement("div");i.classList.add("image-card");const e=document.createElement("a");e.href=r.largeImageURL,e.classList.add("image-link");const t=document.createElement("img");t.src=r.webformatURL,t.alt=r.tags,t.classList.add("image");const o=document.createElement("div");o.classList.add("image-info"),o.innerHTML=`
        <p class="image-likes text">Likes</p>
        <p class="image-views text">Views</p>
        <p class="image-downloads text">Downloads</p>
        <p class="image-comments text">Comments</p>
        <p class="number">${r.likes}</p>
        <p class="number">${r.views}</p>
        <p class="number">${r.downloads}</p>
        <p class="number">${r.comments}</p>
        `,e.appendChild(t),i.appendChild(e),i.appendChild(o),s.appendChild(i)})}const p=document.getElementById("gallery"),c=document.querySelector(".pagebutton");let d="";async function m(a){a.preventDefault();const s=document.getElementById("input").value.trim();if(!s){n.error({title:"Error",message:"Please enter search request!",position:"topRight"});return}d!==s?(y(),d=s):b();const r=document.querySelector(".loader");r.style.visibility="visible";try{const i=await h(s);E(i),new g(".image-link",{captionsData:"alt",captionDelay:500}).refresh()}catch(i){console.error("RENDER ERROR",i),n.error({title:"Error",message:"Failed to load images. Please try again!",position:"topRight"})}finally{r.style.visibility="hidden",p.children.length>0?c.style.visibility="visible":c.style.visibility="hidden"}}document.getElementById("form").addEventListener("submit",a=>{p.innerHTML="",m(a)});document.getElementById("page-button").addEventListener("click",m);
//# sourceMappingURL=index.js.map
